import type { Student, Product } from './schema'

export const FULL_STUDENT_SEED: Array<Pick<Student, 'id' | 'barcode' | 'name' | 'balance' | 'is_vip' | 'is_active'>> = [
  {
    "id": 1,
    "barcode": "STU-0001",
    "name": "Bloom Yair",
    "balance": 45,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 2,
    "barcode": "STU-0002",
    "name": "Friedlander Zev",
    "balance": 80,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 3,
    "barcode": "STU-0003",
    "name": "Haddad Moshe Chaim",
    "balance": 60,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 4,
    "barcode": "STU-0004",
    "name": "Hayon David",
    "balance": 95,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 5,
    "barcode": "STU-0005",
    "name": "Karman Yitzchok",
    "balance": 20,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 6,
    "barcode": "STU-0006",
    "name": "Levitz Avrohom",
    "balance": 70,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 7,
    "barcode": "STU-0007",
    "name": "Rosenfeld Yehuda",
    "balance": 55,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 8,
    "barcode": "STU-0008",
    "name": "Schwartz Moishe Michael",
    "balance": 40,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 9,
    "barcode": "STU-0009",
    "name": "Simon Eliyahu",
    "balance": 65,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 10,
    "barcode": "STU-0010",
    "name": "Berkowitz Avraham",
    "balance": 55,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 11,
    "barcode": "STU-0011",
    "name": "Dinowitz Shmuel",
    "balance": 70,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 12,
    "barcode": "STU-0012",
    "name": "Ettlinger Moshe",
    "balance": 30,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 13,
    "barcode": "STU-0013",
    "name": "Feldman Shraga",
    "balance": 85,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 14,
    "barcode": "STU-0014",
    "name": "Feltman Daniel",
    "balance": 45,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 15,
    "barcode": "STU-0015",
    "name": "Gantz Tzvi",
    "balance": 60,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 16,
    "barcode": "STU-0016",
    "name": "Hickson Shlomo",
    "balance": 25,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 17,
    "barcode": "STU-0017",
    "name": "Mezei Yehuda",
    "balance": 90,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 18,
    "barcode": "STU-0018",
    "name": "Reich Nathan",
    "balance": 50,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 19,
    "barcode": "STU-0019",
    "name": "Teitelbaum Binyamin",
    "balance": 75,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 20,
    "barcode": "STU-0020",
    "name": "Yanni Shimon",
    "balance": 40,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 21,
    "barcode": "STU-0021",
    "name": "Moskowitz Meir Shulem",
    "balance": 65,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 22,
    "barcode": "STU-0022",
    "name": "Goldberg Chaim",
    "balance": 50,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 23,
    "barcode": "STU-0023",
    "name": "Lieberman Yehoshua",
    "balance": 60,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 24,
    "barcode": "STU-0024",
    "name": "Veksler Aron",
    "balance": 45,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 25,
    "barcode": "STU-0025",
    "name": "Shein Dovi",
    "balance": 70,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 26,
    "barcode": "STU-0026",
    "name": "Jakobi Aharon",
    "balance": 35,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 27,
    "barcode": "STU-0027",
    "name": "Stern Aaron",
    "balance": 80,
    "is_vip": false,
    "is_active": true
  },
  {
    "id": 28,
    "barcode": "STU-0028",
    "name": "Sigman Shmuel",
    "balance": 55,
    "is_vip": false,
    "is_active": true
  }
]

export const FULL_PRODUCT_SEED: Array<Pick<Product, 'id' | 'barcode' | 'name' | 'point_cost' | 'quantity' | 'low_stock_threshold' | 'vip_only' | 'is_active' | 'image_url' | 'emoji' | 'category'>> = [
  {
    "id": 1,
    "barcode": "ITEM-0001",
    "name": "Water Bottle",
    "point_cost": 8,
    "quantity": 48,
    "low_stock_threshold": 12,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "💧",
    "category": "drinks"
  },
  {
    "id": 2,
    "barcode": "ITEM-0002",
    "name": "Gatorade Berry",
    "point_cost": 30,
    "quantity": 16,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧃",
    "category": "drinks"
  },
  {
    "id": 3,
    "barcode": "ITEM-0003",
    "name": "Gatorade Lemon Lime",
    "point_cost": 30,
    "quantity": 14,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧃",
    "category": "drinks"
  },
  {
    "id": 4,
    "barcode": "ITEM-0004",
    "name": "Apple Juice Box",
    "point_cost": 18,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧃",
    "category": "drinks"
  },
  {
    "id": 5,
    "barcode": "ITEM-0005",
    "name": "Orange Juice Box",
    "point_cost": 18,
    "quantity": 20,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧃",
    "category": "drinks"
  },
  {
    "id": 6,
    "barcode": "ITEM-0006",
    "name": "Seltzer Can",
    "point_cost": 15,
    "quantity": 30,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥤",
    "category": "drinks"
  },
  {
    "id": 7,
    "barcode": "ITEM-0007",
    "name": "Snapple Peach",
    "point_cost": 35,
    "quantity": 12,
    "low_stock_threshold": 5,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥤",
    "category": "drinks"
  },
  {
    "id": 20,
    "barcode": "ITEM-0020",
    "name": "Pizza Slice",
    "point_cost": 50,
    "quantity": 10,
    "low_stock_threshold": 4,
    "vip_only": true,
    "is_active": true,
    "image_url": "",
    "emoji": "🍕",
    "category": "food"
  },
  {
    "id": 21,
    "barcode": "ITEM-0021",
    "name": "Bagel with Cream Cheese",
    "point_cost": 35,
    "quantity": 16,
    "low_stock_threshold": 5,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥯",
    "category": "food"
  },
  {
    "id": 22,
    "barcode": "ITEM-0022",
    "name": "Plain Bagel",
    "point_cost": 25,
    "quantity": 20,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥯",
    "category": "food"
  },
  {
    "id": 23,
    "barcode": "ITEM-0023",
    "name": "Tuna Sandwich",
    "point_cost": 55,
    "quantity": 8,
    "low_stock_threshold": 3,
    "vip_only": true,
    "is_active": true,
    "image_url": "",
    "emoji": "🥪",
    "category": "food"
  },
  {
    "id": 24,
    "barcode": "ITEM-0024",
    "name": "Egg Salad Sandwich",
    "point_cost": 50,
    "quantity": 8,
    "low_stock_threshold": 3,
    "vip_only": true,
    "is_active": true,
    "image_url": "",
    "emoji": "🥪",
    "category": "food"
  },
  {
    "id": 25,
    "barcode": "ITEM-0025",
    "name": "Hot Pretzel",
    "point_cost": 28,
    "quantity": 18,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥨",
    "category": "food"
  },
  {
    "id": 26,
    "barcode": "ITEM-0026",
    "name": "French Fries Cup",
    "point_cost": 45,
    "quantity": 10,
    "low_stock_threshold": 4,
    "vip_only": true,
    "is_active": true,
    "image_url": "",
    "emoji": "🍟",
    "category": "food"
  },
  {
    "id": 27,
    "barcode": "ITEM-0027",
    "name": "Knish",
    "point_cost": 40,
    "quantity": 12,
    "low_stock_threshold": 4,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥟",
    "category": "food"
  },
  {
    "id": 40,
    "barcode": "ITEM-0040",
    "name": "Paskesz Sour Belts",
    "point_cost": 18,
    "quantity": 32,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍬",
    "category": "nosh"
  },
  {
    "id": 41,
    "barcode": "ITEM-0041",
    "name": "Paskesz Lollycones",
    "point_cost": 15,
    "quantity": 28,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍭",
    "category": "nosh"
  },
  {
    "id": 42,
    "barcode": "ITEM-0042",
    "name": "Sour Sticks",
    "point_cost": 15,
    "quantity": 34,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍬",
    "category": "nosh"
  },
  {
    "id": 43,
    "barcode": "ITEM-0043",
    "name": "Fruit Slices Candy",
    "point_cost": 18,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍬",
    "category": "nosh"
  },
  {
    "id": 44,
    "barcode": "ITEM-0044",
    "name": "Chocolate Bar",
    "point_cost": 22,
    "quantity": 20,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍫",
    "category": "nosh"
  },
  {
    "id": 45,
    "barcode": "ITEM-0045",
    "name": "Klik Chocolate Bag",
    "point_cost": 25,
    "quantity": 16,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍫",
    "category": "nosh"
  },
  {
    "id": 46,
    "barcode": "ITEM-0046",
    "name": "Mike and Ike Box",
    "point_cost": 20,
    "quantity": 22,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍬",
    "category": "nosh"
  },
  {
    "id": 47,
    "barcode": "ITEM-0047",
    "name": "Sour Punch Bites",
    "point_cost": 22,
    "quantity": 18,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍬",
    "category": "nosh"
  },
  {
    "id": 60,
    "barcode": "ITEM-0060",
    "name": "Reisman's Brownie Bar",
    "point_cost": 20,
    "quantity": 18,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍫",
    "category": "cookies"
  },
  {
    "id": 61,
    "barcode": "ITEM-0061",
    "name": "Chocolate Chip Cookie",
    "point_cost": 20,
    "quantity": 30,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍪",
    "category": "cookies"
  },
  {
    "id": 62,
    "barcode": "ITEM-0062",
    "name": "Fresh Cookie",
    "point_cost": 30,
    "quantity": 22,
    "low_stock_threshold": 8,
    "vip_only": true,
    "is_active": true,
    "image_url": "",
    "emoji": "🍪",
    "category": "cookies"
  },
  {
    "id": 63,
    "barcode": "ITEM-0063",
    "name": "Mini Muffin Pack",
    "point_cost": 25,
    "quantity": 18,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧁",
    "category": "cookies"
  },
  {
    "id": 64,
    "barcode": "ITEM-0064",
    "name": "Cupcake",
    "point_cost": 30,
    "quantity": 14,
    "low_stock_threshold": 5,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧁",
    "category": "cookies"
  },
  {
    "id": 65,
    "barcode": "ITEM-0065",
    "name": "Wafer Bar",
    "point_cost": 18,
    "quantity": 26,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍫",
    "category": "cookies"
  },
  {
    "id": 66,
    "barcode": "ITEM-0066",
    "name": "Chocolate Rugelach",
    "point_cost": 28,
    "quantity": 16,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥐",
    "category": "cookies"
  },
  {
    "id": 80,
    "barcode": "ITEM-0080",
    "name": "Pretzel Bag",
    "point_cost": 15,
    "quantity": 36,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥨",
    "category": "snacks"
  },
  {
    "id": 81,
    "barcode": "ITEM-0081",
    "name": "Popcorn Bag",
    "point_cost": 15,
    "quantity": 30,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍿",
    "category": "snacks"
  },
  {
    "id": 82,
    "barcode": "ITEM-0082",
    "name": "Potato Chips",
    "point_cost": 18,
    "quantity": 28,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥔",
    "category": "snacks"
  },
  {
    "id": 83,
    "barcode": "ITEM-0083",
    "name": "BBQ Chips",
    "point_cost": 18,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥔",
    "category": "snacks"
  },
  {
    "id": 84,
    "barcode": "ITEM-0084",
    "name": "Onion Rings Snack",
    "point_cost": 18,
    "quantity": 22,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "⭕",
    "category": "snacks"
  },
  {
    "id": 85,
    "barcode": "ITEM-0085",
    "name": "Bamba Bag",
    "point_cost": 18,
    "quantity": 20,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🥜",
    "category": "snacks"
  },
  {
    "id": 86,
    "barcode": "ITEM-0086",
    "name": "Corn Chips",
    "point_cost": 18,
    "quantity": 22,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🌽",
    "category": "snacks"
  },
  {
    "id": 87,
    "barcode": "ITEM-0087",
    "name": "Granola Bar",
    "point_cost": 16,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "▰",
    "category": "snacks"
  },
  {
    "id": 100,
    "barcode": "ITEM-0100",
    "name": "Klein's Ice Cream Cone",
    "point_cost": 25,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍦",
    "category": "ices"
  },
  {
    "id": 101,
    "barcode": "ITEM-0101",
    "name": "Klein's Ice Cream Sandwich",
    "point_cost": 25,
    "quantity": 20,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍨",
    "category": "ices"
  },
  {
    "id": 102,
    "barcode": "ITEM-0102",
    "name": "Ice Cream Bar",
    "point_cost": 25,
    "quantity": 18,
    "low_stock_threshold": 6,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🍧",
    "category": "ices"
  },
  {
    "id": 103,
    "barcode": "ITEM-0103",
    "name": "Icy Cup",
    "point_cost": 12,
    "quantity": 40,
    "low_stock_threshold": 12,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧊",
    "category": "ices"
  },
  {
    "id": 104,
    "barcode": "ITEM-0104",
    "name": "Slush Cup",
    "point_cost": 15,
    "quantity": 26,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧊",
    "category": "ices"
  },
  {
    "id": 105,
    "barcode": "ITEM-0105",
    "name": "Freeze Pop",
    "point_cost": 10,
    "quantity": 50,
    "low_stock_threshold": 15,
    "vip_only": false,
    "is_active": true,
    "image_url": "",
    "emoji": "🧊",
    "category": "ices"
  },
  {
    "id": 120,
    "barcode": "ITEM-0120",
    "name": "Shufra Wafer Rolls Hazelnut Cream",
    "point_cost": 35,
    "quantity": 14,
    "low_stock_threshold": 5,
    "vip_only": true,
    "is_active": true,
    "image_url": "/store-items/store-items/shufra-wafer-rolls-hazelnut.jpeg",
    "emoji": "🍪",
    "category": "cookies"
  },
  {
    "id": 121,
    "barcode": "ITEM-0121",
    "name": "Shufra Filled Twist Bites Strawberry",
    "point_cost": 35,
    "quantity": 12,
    "low_stock_threshold": 4,
    "vip_only": true,
    "is_active": true,
    "image_url": "/store-items/store-items/shufra-filled-twist-bites-strawberry.jpg",
    "emoji": "🍬",
    "category": "nosh"
  },
  {
    "id": 122,
    "barcode": "ITEM-0122",
    "name": "Gross & Co Nut Crunch Mini Chocolate Bars",
    "point_cost": 35,
    "quantity": 12,
    "low_stock_threshold": 4,
    "vip_only": true,
    "is_active": true,
    "image_url": "/store-items/store-items/gross-nut-crunch.jpg",
    "emoji": "🍫",
    "category": "nosh"
  },
  {
    "id": 123,
    "barcode": "ITEM-0123",
    "name": "Gross & Co Chocolate Crema Caramel",
    "point_cost": 30,
    "quantity": 10,
    "low_stock_threshold": 4,
    "vip_only": true,
    "is_active": true,
    "image_url": "/store-items/store-items/gross-chocolate-crema-caramel.png",
    "emoji": "🍫",
    "category": "nosh"
  },
  {
    "id": 124,
    "barcode": "ITEM-0124",
    "name": "Gross & Co Chocolate Leaves Hazelnuts",
    "point_cost": 30,
    "quantity": 14,
    "low_stock_threshold": 5,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/gross-chocolate-leaves-hazelnut.jpg",
    "emoji": "🍫",
    "category": "nosh"
  },
  {
    "id": 125,
    "barcode": "ITEM-0125",
    "name": "Shufra Snow Flakes Talafel",
    "point_cost": 18,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/shufra-snow-flakes-talafel.jpg",
    "emoji": "▰",
    "category": "snacks"
  },
  {
    "id": 126,
    "barcode": "ITEM-0126",
    "name": "Shufra Snow Flakes Onion",
    "point_cost": 18,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/shufra-snow-flakes-onion.png",
    "emoji": "▰",
    "category": "snacks"
  },
  {
    "id": 127,
    "barcode": "ITEM-0127",
    "name": "Shufra Pretzels Shapes",
    "point_cost": 18,
    "quantity": 30,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/shufra-pretzels-shapes.jpg",
    "emoji": "🥨",
    "category": "snacks"
  },
  {
    "id": 128,
    "barcode": "ITEM-0128",
    "name": "Shufra Pretzels Mini",
    "point_cost": 18,
    "quantity": 30,
    "low_stock_threshold": 10,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/shufra-pretzels-mini.jpg",
    "emoji": "🥨",
    "category": "snacks"
  },
  {
    "id": 129,
    "barcode": "ITEM-0129",
    "name": "Gesher Snak Pak Ketchup",
    "point_cost": 18,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/gesher-snak-pak-ketchup.png",
    "emoji": "▰",
    "category": "snacks"
  },
  {
    "id": 130,
    "barcode": "ITEM-0130",
    "name": "Gesher Snak Pak Hot & Spicy",
    "point_cost": 18,
    "quantity": 24,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/gesher-snak-pak-hot-spicy.png",
    "emoji": "▰",
    "category": "snacks"
  },
  {
    "id": 131,
    "barcode": "ITEM-0131",
    "name": "Beigel Beigel Sesame Sticks",
    "point_cost": 20,
    "quantity": 22,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/beigel-sesame-sticks.png",
    "emoji": "🥨",
    "category": "snacks"
  },
  {
    "id": 132,
    "barcode": "ITEM-0132",
    "name": "Beigel Beigel Thin Pretzel Sticks",
    "point_cost": 20,
    "quantity": 22,
    "low_stock_threshold": 8,
    "vip_only": false,
    "is_active": true,
    "image_url": "/store-items/store-items/beigel-thin-pretzel-sticks.png",
    "emoji": "🥨",
    "category": "snacks"
  }
]
