begin;

create schema if not exists public;

-- Base schema for secure Yeshiva Ketana deployment.
-- No Intake/Admissions tables.
-- No anonymous-access policies.
-- No demo student data inserts.

------------------------------------------------------------
-- Core students table
------------------------------------------------------------

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  name text not null,
  class_name text not null default '',
  division text not null default 'yeshiva-ketana',
  status text not null default 'present',
  daily_status text,
  late_details jsonb,
  with_staff text,
  token_balance integer not null default 0,
  reminders integer not null default 0,
  attendance jsonb not null default '[]'::jsonb,
  notes jsonb not null default '[]'::jsonb,
  behavior_log jsonb not null default '[]'::jsonb,
  parent_calls jsonb not null default '[]'::jsonb,
  test_scores jsonb not null default '[]'::jsonb,
  class_log jsonb not null default '[]'::jsonb,
  services jsonb not null default '[]'::jsonb,
  breakfast jsonb not null default '[]'::jsonb,
  detention boolean not null default false,
  iep boolean not null default false,
  iep_details text not null default '',
  medical jsonb not null default '{}'::jsonb,
  family jsonb not null default '{}'::jsonb,
  therapy_assignments jsonb not null default '[]'::jsonb,
  assigned_therapist text,
  therapy_frequency text,
  therapy_notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists students_name_idx on public.students(name);
create index if not exists students_division_idx on public.students(division);
create index if not exists students_class_name_idx on public.students(class_name);
create index if not exists idx_students_attendance_gin on public.students using gin(attendance);
create index if not exists idx_students_notes_gin on public.students using gin(notes);
create index if not exists idx_students_behavior_log_gin on public.students using gin(behavior_log);
create index if not exists idx_students_parent_calls_gin on public.students using gin(parent_calls);
create index if not exists idx_students_test_scores_gin on public.students using gin(test_scores);
create index if not exists idx_students_class_log_gin on public.students using gin(class_log);
create index if not exists idx_students_therapy_assignments_gin on public.students using gin(therapy_assignments);

create or replace function public.students_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists students_set_updated_at_trigger on public.students;
create trigger students_set_updated_at_trigger
before update on public.students
for each row
execute function public.students_set_updated_at();

------------------------------------------------------------
-- Staff + login sessions
------------------------------------------------------------

create table if not exists public.staff (
  id bigserial primary key,
  name text not null unique,
  role text not null default 'staff',
  roles text[] not null default array['staff']::text[],
  email text,
  phone text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_staff_name on public.staff(name);
create index if not exists idx_staff_active on public.staff(active);
create index if not exists idx_staff_roles_gin on public.staff using gin(roles);

create table if not exists public.login_sessions (
  id bigserial primary key,
  staff_id bigint not null references public.staff(id) on delete cascade,
  staff_name text not null,
  role text not null,
  login_time timestamptz not null default now(),
  logout_time timestamptz,
  session_duration_seconds integer,
  created_at timestamptz not null default now()
);

create index if not exists idx_login_sessions_staff_id on public.login_sessions(staff_id);
create index if not exists idx_login_sessions_login_time on public.login_sessions(login_time desc);
create index if not exists idx_login_sessions_staff_name on public.login_sessions(staff_name);

------------------------------------------------------------
-- Points events + store
------------------------------------------------------------

create table if not exists public.points_events (
  id bigint generated always as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  student_id bigint not null references public.students(id) on delete cascade,
  student_name text not null,
  staff_id text,
  staff_name text not null,
  staff_role text not null default 'staff',
  points_delta integer not null,
  event_type text not null,
  category text not null,
  reason text not null,
  note text,
  source_page text,
  source_context text,
  related_event_id bigint references public.points_events(id),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists points_events_student_id_created_at_idx
  on public.points_events (student_id, created_at desc);
create index if not exists points_events_created_at_idx
  on public.points_events (created_at desc);
create index if not exists points_events_staff_name_created_at_idx
  on public.points_events (staff_name, created_at desc);
create index if not exists points_events_category_created_at_idx
  on public.points_events (category, created_at desc);
create unique index if not exists points_events_reversal_related_event_uidx
  on public.points_events (related_event_id)
  where related_event_id is not null and event_type = 'reversal';

create table if not exists public.store_items (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text not null default '',
  barcode text not null default '',
  category text not null default 'nosh',
  cost integer not null default 0 check (cost >= 0),
  emoji text not null default '',
  vip boolean not null default false,
  stock integer not null default 0 check (stock >= 0),
  low_stock_at integer not null default 0 check (low_stock_at >= 0),
  image_url text not null default '',
  active boolean not null default true,
  updated_by text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists store_items_active_category_idx
  on public.store_items (active, category, name);
create index if not exists store_items_stock_idx
  on public.store_items (stock, low_stock_at);
create index if not exists store_items_sku_idx
  on public.store_items (sku)
  where sku <> '';
create index if not exists store_items_barcode_idx
  on public.store_items (barcode)
  where barcode <> '';

create table if not exists public.store_redemptions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  student_id bigint references public.students(id) on delete set null,
  student_name text not null,
  item_id bigint references public.store_items(id) on delete set null,
  item_name text not null,
  cost integer not null check (cost >= 0),
  staff_name text not null,
  source text not null default 'token-store',
  metadata jsonb not null default '{}'::jsonb,
  idempotency_key text,
  points_event_id bigint references public.points_events(id),
  resulting_balance integer,
  resulting_stock integer,
  reversed_at timestamptz,
  reversed_by text,
  reversal_event_id bigint references public.points_events(id),
  reversal_note text
);

create index if not exists store_redemptions_created_at_idx
  on public.store_redemptions (created_at desc);
create index if not exists store_redemptions_student_id_created_at_idx
  on public.store_redemptions (student_id, created_at desc);
create index if not exists store_redemptions_item_id_created_at_idx
  on public.store_redemptions (item_id, created_at desc);
create unique index if not exists store_redemptions_idempotency_key_uidx
  on public.store_redemptions (idempotency_key)
  where idempotency_key is not null;
create unique index if not exists store_redemptions_points_event_id_uidx
  on public.store_redemptions (points_event_id)
  where points_event_id is not null;
create index if not exists store_redemptions_points_event_id_idx
  on public.store_redemptions (points_event_id)
  where points_event_id is not null;

------------------------------------------------------------
-- Setup center + operational config
------------------------------------------------------------

create table if not exists public.teaching_actions (
  id text primary key,
  label text not null unique,
  points integer not null,
  category text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_teaching_actions_category on public.teaching_actions(category);

create table if not exists public.vip_rules (
  id text primary key default 'default',
  minimum_points integer not null default 80,
  maximum_reminders integer not null default 2,
  minimum_attendance integer not null default 90,
  require_all boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.store_sales (
  id text primary key,
  name text not null,
  type text not null,
  value integer not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_store_sales_active on public.store_sales(active);
create index if not exists idx_store_sales_type on public.store_sales(type);

create table if not exists public.setup_assignments (
  staff_name text primary key,
  assignments_data jsonb default '{"periods":{"1":[],"2":[],"3":[]},"caseload":[]}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.therapy_schedule (
  id int primary key default 1,
  schedule_data jsonb default '[]'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.staff_accounts (
  staff_name text primary key,
  account_data jsonb default '{"active":true,"divisions":"both"}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_setup_assignments_data_gin on public.setup_assignments using gin(assignments_data);
create index if not exists idx_therapy_schedule_data_gin on public.therapy_schedule using gin(schedule_data);
create index if not exists idx_staff_accounts_data_gin on public.staff_accounts using gin(account_data);

------------------------------------------------------------
-- Student support + notes + flags + todos
------------------------------------------------------------

create table if not exists public.support_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  started_at timestamptz not null default timezone('utc', now()),
  ended_at timestamptz,
  student_id bigint references public.students(id) on delete cascade,
  student_name text not null,
  staff_id text,
  staff_name text not null,
  service_type text not null,
  return_location text,
  notes text,
  goal_worked_on text,
  student_response text,
  follow_up_needed boolean not null default false
);

create index if not exists support_sessions_student_id_started_at_idx
  on public.support_sessions (student_id, started_at desc);
create index if not exists support_sessions_staff_id_started_at_idx
  on public.support_sessions (staff_id, started_at desc);

create table if not exists public.student_notes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  student_id bigint references public.students(id) on delete cascade,
  student_name text not null,
  note text not null,
  author text not null
);

create index if not exists student_notes_student_id_created_at_idx
  on public.student_notes (student_id, created_at desc);

create table if not exists public.student_flags (
  id text primary key,
  student_id bigint references public.students(id) on delete cascade,
  payload jsonb not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists student_flags_student_id_idx on public.student_flags(student_id);
create index if not exists student_flags_created_at_idx on public.student_flags(created_at desc);

create table if not exists public.todos (
  id bigint generated always as identity primary key,
  date text not null,
  time text,
  text text not null,
  category text not null default 'general',
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_todos_date on public.todos(date desc);
create index if not exists idx_todos_done on public.todos(done);
create index if not exists idx_todos_category on public.todos(category);

------------------------------------------------------------
-- Academics + assignments
------------------------------------------------------------

create table if not exists public.grade_entries (
  id text primary key,
  student_id integer not null references public.students(id) on delete cascade,
  teacher text not null,
  subject text not null,
  skill text not null default '',
  assessment_name text not null,
  assessment_type text not null default 'Quiz',
  date date not null,
  score_type text not null default 'points',
  score integer,
  max_score integer,
  rating text,
  attempt_status text not null default 'scored',
  grading_method text not null default 'points',
  notes text not null default '',
  entered_by text not null default 'Staff',
  entered_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  source_context text not null default 'manual'
);

create index if not exists idx_grade_entries_student on public.grade_entries(student_id);
create index if not exists idx_grade_entries_teacher on public.grade_entries(teacher);
create index if not exists idx_grade_entries_subject on public.grade_entries(subject);
create index if not exists idx_grade_entries_date on public.grade_entries(date desc);

create table if not exists public.student_class_assignments (
  student_id integer primary key references public.students(id) on delete cascade,
  class_id text not null default '',
  division_key text not null default '',
  updated_at timestamptz not null default now(),
  updated_by text not null default 'Admin'
);

create index if not exists idx_sca_class_id on public.student_class_assignments(class_id);
create index if not exists idx_sca_division_key on public.student_class_assignments(division_key);

create table if not exists public.teacher_rebbe_assignments (
  id text primary key,
  student_id integer not null references public.students(id) on delete cascade,
  teacher_name text not null,
  subject text not null default '',
  class_or_group text not null default '',
  period text not null default '',
  weekdays text[] not null default array[]::text[],
  start_date date,
  end_date date,
  assignment_type text not null default 'additional' check (assignment_type in ('primary', 'additional')),
  status text not null default 'active' check (status in ('active', 'inactive')),
  updated_by text not null default 'System',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_teacher_rebbe_assignments_teacher on public.teacher_rebbe_assignments(teacher_name);
create index if not exists idx_teacher_rebbe_assignments_student on public.teacher_rebbe_assignments(student_id);
create index if not exists idx_teacher_rebbe_assignments_status on public.teacher_rebbe_assignments(status);

------------------------------------------------------------
-- Trigger helpers
------------------------------------------------------------

create or replace function public.set_updated_at_now()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_todos_updated_at_trigger on public.todos;
create trigger update_todos_updated_at_trigger
before update on public.todos
for each row
execute function public.set_updated_at_now();

drop trigger if exists update_teaching_actions_updated_at_trigger on public.teaching_actions;
create trigger update_teaching_actions_updated_at_trigger
before update on public.teaching_actions
for each row
execute function public.set_updated_at_now();

drop trigger if exists update_vip_rules_updated_at_trigger on public.vip_rules;
create trigger update_vip_rules_updated_at_trigger
before update on public.vip_rules
for each row
execute function public.set_updated_at_now();

drop trigger if exists update_store_sales_updated_at_trigger on public.store_sales;
create trigger update_store_sales_updated_at_trigger
before update on public.store_sales
for each row
execute function public.set_updated_at_now();

drop trigger if exists grade_entries_updated_at on public.grade_entries;
create trigger grade_entries_updated_at
before update on public.grade_entries
for each row
execute function public.set_updated_at_now();

drop trigger if exists sca_updated_at on public.student_class_assignments;
create trigger sca_updated_at
before update on public.student_class_assignments
for each row
execute function public.set_updated_at_now();

drop trigger if exists teacher_rebbe_assignments_updated_at on public.teacher_rebbe_assignments;
create trigger teacher_rebbe_assignments_updated_at
before update on public.teacher_rebbe_assignments
for each row
execute function public.set_updated_at_now();

------------------------------------------------------------
-- Transactional RPC functions used by app
------------------------------------------------------------

create or replace function public.apply_points_event_tx(
  p_student_id bigint,
  p_points_delta integer,
  p_staff_name text,
  p_staff_role text default 'staff',
  p_event_type text default 'adjustment',
  p_category text default 'admin',
  p_reason text default 'Adjustment',
  p_note text default null,
  p_source_page text default null,
  p_source_context text default null,
  p_related_event_id bigint default null,
  p_metadata jsonb default '{}'::jsonb,
  p_reminder_delta integer default 0,
  p_student_name text default null,
  p_staff_id text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student public.students%rowtype;
  v_event_id bigint;
  v_student_name text;
  v_next_points integer;
  v_next_reminders integer;
  v_metadata jsonb;
begin
  select *
  into v_student
  from public.students
  where id = p_student_id
  for update;

  if not found then
    raise exception 'Student % was not found.', p_student_id;
  end if;

  v_student_name := coalesce(nullif(trim(p_student_name), ''), nullif(trim(v_student.name), ''), 'Unknown Student');
  v_next_points := greatest(0, coalesce(v_student.token_balance, 0) + coalesce(p_points_delta, 0));
  v_next_reminders := greatest(0, coalesce(v_student.reminders, 0) + coalesce(p_reminder_delta, 0));
  v_metadata := coalesce(p_metadata, '{}'::jsonb) || jsonb_build_object('reminderDelta', coalesce(p_reminder_delta, 0));

  insert into public.points_events (
    student_id,
    student_name,
    staff_id,
    staff_name,
    staff_role,
    points_delta,
    event_type,
    category,
    reason,
    note,
    source_page,
    source_context,
    related_event_id,
    metadata
  ) values (
    p_student_id,
    v_student_name,
    p_staff_id,
    coalesce(nullif(trim(p_staff_name), ''), 'Staff'),
    coalesce(nullif(trim(p_staff_role), ''), 'staff'),
    coalesce(p_points_delta, 0),
    coalesce(nullif(trim(p_event_type), ''), 'adjustment'),
    coalesce(nullif(trim(p_category), ''), 'admin'),
    coalesce(nullif(trim(p_reason), ''), 'Adjustment'),
    p_note,
    p_source_page,
    p_source_context,
    p_related_event_id,
    v_metadata
  )
  returning id into v_event_id;

  update public.students
  set token_balance = v_next_points,
      reminders = v_next_reminders
  where id = p_student_id;

  return jsonb_build_object(
    'event_id', v_event_id,
    'student_id', p_student_id,
    'next_points', v_next_points,
    'next_reminders', v_next_reminders
  );
end;
$$;

create or replace function public.redeem_store_purchase_tx(
  p_student_id bigint,
  p_item_id bigint,
  p_staff_name text,
  p_staff_role text default 'staff',
  p_idempotency_key text default null,
  p_source text default 'token-store',
  p_metadata jsonb default '{}'::jsonb,
  p_reason text default null,
  p_note text default null,
  p_source_page text default 'store',
  p_source_context text default 'token-store-redeem'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.store_redemptions%rowtype;
  v_student public.students%rowtype;
  v_item public.store_items%rowtype;
  v_event_id bigint;
  v_redemption_id bigint;
  v_next_points integer;
  v_next_stock integer;
  v_reason text;
begin
  if p_idempotency_key is null or length(trim(p_idempotency_key)) = 0 then
    raise exception 'idempotency_key is required.';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_idempotency_key, 0));

  select *
  into v_existing
  from public.store_redemptions
  where idempotency_key = p_idempotency_key
  limit 1;

  if found then
    return jsonb_build_object(
      'status', 'duplicate_completed',
      'redemption_id', v_existing.id,
      'points_event_id', v_existing.points_event_id,
      'next_points', v_existing.resulting_balance,
      'next_stock', v_existing.resulting_stock,
      'student_id', v_existing.student_id,
      'item_id', v_existing.item_id
    );
  end if;

  select *
  into v_student
  from public.students
  where id = p_student_id
  for update;

  if not found then
    raise exception 'Student % was not found.', p_student_id;
  end if;

  select *
  into v_item
  from public.store_items
  where id = p_item_id
  for update;

  if not found then
    raise exception 'Store item % was not found.', p_item_id;
  end if;

  if coalesce(v_item.active, false) is false then
    raise exception 'Store item % is inactive.', p_item_id;
  end if;

  if coalesce(v_item.stock, 0) <= 0 then
    raise exception '% is out of stock.', v_item.name;
  end if;

  if coalesce(v_student.token_balance, 0) < coalesce(v_item.cost, 0) then
    raise exception '% does not have enough points.', coalesce(v_student.name, 'Student');
  end if;

  v_next_points := greatest(0, coalesce(v_student.token_balance, 0) - coalesce(v_item.cost, 0));
  v_next_stock := coalesce(v_item.stock, 0) - 1;
  v_reason := coalesce(nullif(trim(p_reason), ''), format('Store purchase: %s', coalesce(v_item.name, 'Item')));

  insert into public.points_events (
    student_id,
    student_name,
    staff_id,
    staff_name,
    staff_role,
    points_delta,
    event_type,
    category,
    reason,
    note,
    source_page,
    source_context,
    metadata
  ) values (
    v_student.id,
    coalesce(v_student.name, 'Unknown Student'),
    null,
    coalesce(nullif(trim(p_staff_name), ''), 'Register'),
    coalesce(nullif(trim(p_staff_role), ''), 'staff'),
    -coalesce(v_item.cost, 0),
    'purchase',
    'store',
    v_reason,
    p_note,
    p_source_page,
    p_source_context,
    coalesce(p_metadata, '{}'::jsonb) || jsonb_build_object('itemId', v_item.id, 'itemName', v_item.name, 'itemCost', v_item.cost, 'idempotencyKey', p_idempotency_key, 'reminderDelta', 0)
  )
  returning id into v_event_id;

  update public.students
  set token_balance = v_next_points
  where id = v_student.id;

  update public.store_items
  set stock = v_next_stock,
      updated_by = coalesce(nullif(trim(p_staff_name), ''), 'Register'),
      updated_at = now()
  where id = v_item.id;

  begin
    insert into public.store_redemptions (
      student_id,
      student_name,
      item_id,
      item_name,
      cost,
      staff_name,
      source,
      metadata,
      idempotency_key,
      points_event_id,
      resulting_balance,
      resulting_stock
    ) values (
      v_student.id,
      coalesce(v_student.name, 'Unknown Student'),
      v_item.id,
      coalesce(v_item.name, 'Unknown Item'),
      coalesce(v_item.cost, 0),
      coalesce(nullif(trim(p_staff_name), ''), 'Register'),
      coalesce(nullif(trim(p_source), ''), 'token-store'),
      coalesce(p_metadata, '{}'::jsonb),
      p_idempotency_key,
      v_event_id,
      v_next_points,
      v_next_stock
    )
    returning id into v_redemption_id;
  exception
    when unique_violation then
      select *
      into v_existing
      from public.store_redemptions
      where idempotency_key = p_idempotency_key
      limit 1;

      if found then
        return jsonb_build_object(
          'status', 'duplicate_completed',
          'redemption_id', v_existing.id,
          'points_event_id', v_existing.points_event_id,
          'next_points', v_existing.resulting_balance,
          'next_stock', v_existing.resulting_stock,
          'student_id', v_existing.student_id,
          'item_id', v_existing.item_id
        );
      end if;

      raise exception 'Store redemption unique constraint violation occurred, but no completed idempotent row was found for key %.', p_idempotency_key;
  end;

  return jsonb_build_object(
    'status', 'created',
    'redemption_id', v_redemption_id,
    'points_event_id', v_event_id,
    'next_points', v_next_points,
    'next_stock', v_next_stock,
    'student_id', v_student.id,
    'item_id', v_item.id
  );
end;
$$;

create or replace function public.reverse_points_event_tx(
  p_target_event_id bigint,
  p_staff_name text,
  p_staff_role text default 'staff',
  p_note text default null,
  p_source_context text default 'history-undo'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_target public.points_events%rowtype;
  v_target_locked public.points_events%rowtype;
  v_student public.students%rowtype;
  v_original_reminder_delta integer;
  v_reversal_points_delta integer;
  v_reversal_reminder_delta integer;
  v_next_points integer;
  v_next_reminders integer;
  v_reversal_event_id bigint;
begin
  select *
  into v_target
  from public.points_events
  where id = p_target_event_id;

  if not found then
    raise exception 'Points event % was not found.', p_target_event_id;
  end if;

  if v_target.event_type = 'reversal' then
    raise exception 'Points event % is already a reversal event.', p_target_event_id;
  end if;

  if v_target.event_type = 'purchase' or v_target.category = 'store' then
    raise exception 'Store purchase events must be reversed with reverse_store_purchase_tx.';
  end if;

  if exists (
    select 1
    from public.points_events pe
    where pe.related_event_id = p_target_event_id
      and pe.event_type = 'reversal'
  ) then
    raise exception 'Points event % has already been reversed.', p_target_event_id;
  end if;

  select *
  into v_student
  from public.students
  where id = v_target.student_id
  for update;

  if not found then
    raise exception 'Student % was not found for points event %.', v_target.student_id, p_target_event_id;
  end if;

  select *
  into v_target_locked
  from public.points_events
  where id = p_target_event_id
  for update;

  if v_target_locked.event_type = 'reversal' then
    raise exception 'Points event % is already a reversal event.', p_target_event_id;
  end if;

  if exists (
    select 1
    from public.points_events pe
    where pe.related_event_id = p_target_event_id
      and pe.event_type = 'reversal'
  ) then
    raise exception 'Points event % has already been reversed.', p_target_event_id;
  end if;

  v_original_reminder_delta := coalesce((v_target_locked.metadata ->> 'reminderDelta')::integer, case when v_target_locked.event_type = 'reminder' then 1 else 0 end);
  v_reversal_points_delta := -coalesce(v_target_locked.points_delta, 0);
  v_reversal_reminder_delta := -v_original_reminder_delta;
  v_next_points := greatest(0, coalesce(v_student.token_balance, 0) + v_reversal_points_delta);
  v_next_reminders := greatest(0, coalesce(v_student.reminders, 0) + v_reversal_reminder_delta);

  insert into public.points_events (
    student_id,
    student_name,
    staff_id,
    staff_name,
    staff_role,
    points_delta,
    event_type,
    category,
    reason,
    note,
    source_page,
    source_context,
    related_event_id,
    metadata
  ) values (
    v_target_locked.student_id,
    coalesce(v_target_locked.student_name, v_student.name, 'Unknown Student'),
    null,
    coalesce(nullif(trim(p_staff_name), ''), 'Staff'),
    coalesce(nullif(trim(p_staff_role), ''), 'staff'),
    v_reversal_points_delta,
    'reversal',
    v_target_locked.category,
    format('Undo: %s', v_target_locked.reason),
    coalesce(p_note, format('Reversed event #%s', v_target_locked.id)),
    coalesce(v_target_locked.source_page, v_target_locked.category),
    coalesce(nullif(trim(p_source_context), ''), 'history-undo'),
    v_target_locked.id,
    jsonb_build_object(
      'reversedEventId', v_target_locked.id,
      'originalEventType', v_target_locked.event_type,
      'originalPointsDelta', coalesce(v_target_locked.points_delta, 0),
      'originalReminderDelta', v_original_reminder_delta,
      'reminderDelta', v_reversal_reminder_delta
    )
  )
  returning id into v_reversal_event_id;

  update public.students
  set token_balance = v_next_points,
      reminders = v_next_reminders
  where id = v_student.id;

  return jsonb_build_object(
    'status', 'reversed',
    'reversal_event_id', v_reversal_event_id,
    'target_event_id', v_target_locked.id,
    'student_id', v_student.id,
    'next_points', v_next_points,
    'next_reminders', v_next_reminders
  );
end;
$$;

create or replace function public.reverse_store_purchase_tx(
  p_target_points_event_id bigint,
  p_staff_name text,
  p_staff_role text default 'staff',
  p_note text default null,
  p_source_context text default 'history-undo'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_redemption public.store_redemptions%rowtype;
  v_redemption_locked public.store_redemptions%rowtype;
  v_original_event public.points_events%rowtype;
  v_original_event_locked public.points_events%rowtype;
  v_student public.students%rowtype;
  v_item public.store_items%rowtype;
  v_reversal_event_id bigint;
  v_next_points integer;
  v_next_stock integer;
  v_reversal_points_delta integer;
begin
  select *
  into v_redemption
  from public.store_redemptions
  where points_event_id = p_target_points_event_id
  limit 1;

  if not found then
    raise exception 'Store purchase reversal is unavailable for this historical purchase because it is not linked to a store_redemptions row.';
  end if;

  if v_redemption.points_event_id is null then
    raise exception 'Store purchase reversal is unavailable for this historical purchase because it is not linked to a points event.';
  end if;

  if v_redemption.reversed_at is not null then
    raise exception 'Store redemption % has already been reversed.', v_redemption.id;
  end if;

  if v_redemption.student_id is null or v_redemption.item_id is null then
    raise exception 'Store redemption % cannot be reversed because student/item references are missing.', v_redemption.id;
  end if;

  select *
  into v_student
  from public.students
  where id = v_redemption.student_id
  for update;

  if not found then
    raise exception 'Student % was not found for store redemption %.', v_redemption.student_id, v_redemption.id;
  end if;

  select *
  into v_item
  from public.store_items
  where id = v_redemption.item_id
  for update;

  if not found then
    raise exception 'Store item % was not found for store redemption %.', v_redemption.item_id, v_redemption.id;
  end if;

  select *
  into v_redemption_locked
  from public.store_redemptions
  where id = v_redemption.id
  for update;

  if v_redemption_locked.reversed_at is not null then
    raise exception 'Store redemption % has already been reversed.', v_redemption_locked.id;
  end if;

  select *
  into v_original_event
  from public.points_events
  where id = p_target_points_event_id;

  if not found then
    raise exception 'Original purchase points event % was not found.', p_target_points_event_id;
  end if;

  if v_original_event.event_type = 'reversal' then
    raise exception 'Points event % is already a reversal event.', p_target_points_event_id;
  end if;

  if v_original_event.event_type <> 'purchase' then
    raise exception 'Points event % is not a purchase event.', p_target_points_event_id;
  end if;

  if exists (
    select 1
    from public.points_events pe
    where pe.related_event_id = p_target_points_event_id
      and pe.event_type = 'reversal'
  ) then
    raise exception 'Store purchase points event % has already been reversed.', p_target_points_event_id;
  end if;

  select *
  into v_original_event_locked
  from public.points_events
  where id = p_target_points_event_id
  for update;

  if exists (
    select 1
    from public.points_events pe
    where pe.related_event_id = p_target_points_event_id
      and pe.event_type = 'reversal'
  ) then
    raise exception 'Store purchase points event % has already been reversed.', p_target_points_event_id;
  end if;

  v_reversal_points_delta := abs(coalesce(v_original_event_locked.points_delta, 0));
  v_next_points := greatest(0, coalesce(v_student.token_balance, 0) + v_reversal_points_delta);
  v_next_stock := coalesce(v_item.stock, 0) + 1;

  insert into public.points_events (
    student_id,
    student_name,
    staff_id,
    staff_name,
    staff_role,
    points_delta,
    event_type,
    category,
    reason,
    note,
    source_page,
    source_context,
    related_event_id,
    metadata
  ) values (
    v_original_event_locked.student_id,
    coalesce(v_original_event_locked.student_name, v_student.name, 'Unknown Student'),
    null,
    coalesce(nullif(trim(p_staff_name), ''), 'Staff'),
    coalesce(nullif(trim(p_staff_role), ''), 'staff'),
    v_reversal_points_delta,
    'reversal',
    'store',
    format('Undo store purchase: %s', coalesce(v_redemption_locked.item_name, 'Item')),
    coalesce(p_note, format('Reversed store redemption #%s', v_redemption_locked.id)),
    coalesce(v_original_event_locked.source_page, 'store'),
    coalesce(nullif(trim(p_source_context), ''), 'history-undo'),
    v_original_event_locked.id,
    jsonb_build_object(
      'reversedEventId', v_original_event_locked.id,
      'originalEventType', v_original_event_locked.event_type,
      'itemId', v_redemption_locked.item_id,
      'itemName', v_redemption_locked.item_name,
      'itemCost', v_redemption_locked.cost,
      'redemptionId', v_redemption_locked.id,
      'reminderDelta', 0
    )
  )
  returning id into v_reversal_event_id;

  update public.students
  set token_balance = v_next_points
  where id = v_student.id;

  update public.store_items
  set stock = v_next_stock,
      updated_by = coalesce(nullif(trim(p_staff_name), ''), 'Staff'),
      updated_at = now()
  where id = v_item.id;

  update public.store_redemptions
  set reversed_at = now(),
      reversed_by = coalesce(nullif(trim(p_staff_name), ''), 'Staff'),
      reversal_event_id = v_reversal_event_id,
      reversal_note = p_note
  where id = v_redemption_locked.id;

  return jsonb_build_object(
    'status', 'reversed',
    'redemption_id', v_redemption_locked.id,
    'target_event_id', v_original_event_locked.id,
    'reversal_event_id', v_reversal_event_id,
    'student_id', v_student.id,
    'item_id', v_item.id,
    'next_points', v_next_points,
    'next_stock', v_next_stock
  );
end;
$$;

------------------------------------------------------------
-- Realtime publication entries (safe/idempotent)
------------------------------------------------------------

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'support_sessions'
    ) then
      execute 'alter publication supabase_realtime add table public.support_sessions';
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'student_notes'
    ) then
      execute 'alter publication supabase_realtime add table public.student_notes';
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'grade_entries'
    ) then
      execute 'alter publication supabase_realtime add table public.grade_entries';
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'student_class_assignments'
    ) then
      execute 'alter publication supabase_realtime add table public.student_class_assignments';
    end if;

    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'teacher_rebbe_assignments'
    ) then
      execute 'alter publication supabase_realtime add table public.teacher_rebbe_assignments';
    end if;
  end if;
end $$;

commit;
