create table if not exists public.store_items (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'nosh',
  cost integer not null default 0 check (cost >= 0),
  emoji text not null default '',
  vip boolean not null default false,
  stock integer not null default 0 check (stock >= 0),
  low_stock_at integer not null default 0 check (low_stock_at >= 0),
  image_url text not null default '',
  active boolean not null default true,
  updated_by text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists store_items_active_category_idx
  on public.store_items (active, category, name);

create index if not exists store_items_stock_idx
  on public.store_items (stock, low_stock_at);

create table if not exists public.store_redemptions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  student_id bigint references public.students(id) on delete set null,
  student_name text not null,
  item_id bigint references public.store_items(id) on delete set null,
  item_name text not null,
  cost integer not null check (cost >= 0),
  staff_name text not null,
  source text not null default 'token-store',
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists store_redemptions_created_at_idx
  on public.store_redemptions (created_at desc);

create index if not exists store_redemptions_student_id_created_at_idx
  on public.store_redemptions (student_id, created_at desc);

create index if not exists store_redemptions_item_id_created_at_idx
  on public.store_redemptions (item_id, created_at desc);

comment on table public.store_items is
  'Inventory for Token Store. Includes active flag for soft-removal and editable cost/stock metadata.';

comment on table public.store_redemptions is
  'Append-only log of token-store redemptions with student/item snapshot fields for audit readability.';

comment on column public.store_redemptions.metadata is
  'Flexible JSON metadata for client context (division, role, source workflow details, etc.).';
