begin;

create table if not exists public.support_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  started_at timestamptz not null default timezone('utc', now()),
  ended_at timestamptz,
  student_id bigint references public.students(id) on delete cascade,
  student_name text not null,
  staff_id text,
  staff_name text not null,
  service_type text not null,
  return_location text,
  notes text,
  goal_worked_on text,
  student_response text,
  follow_up_needed boolean not null default false
);

create index if not exists support_sessions_student_id_started_at_idx
  on public.support_sessions (student_id, started_at desc);

create index if not exists support_sessions_staff_id_started_at_idx
  on public.support_sessions (staff_id, started_at desc);

create table if not exists public.student_notes (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  student_id bigint references public.students(id) on delete cascade,
  student_name text not null,
  note text not null,
  author text not null
);

create index if not exists student_notes_student_id_created_at_idx
  on public.student_notes (student_id, created_at desc);

comment on table public.support_sessions is
  'Persisted support session lifecycle records for therapist and support workflows.';

comment on table public.student_notes is
  'Audit log of staff notes written against student records.';

commit;
