begin;

------------------------------------------------------------
-- 1) Student archive columns (soft-delete by default)
------------------------------------------------------------

alter table public.students add column if not exists is_active boolean;
alter table public.students add column if not exists archived_at timestamptz;
alter table public.students add column if not exists archived_by text;

update public.students
set is_active = coalesce(is_active, true)
where true;

alter table public.students
  alter column is_active set default true,
  alter column is_active set not null;

create index if not exists students_is_active_idx on public.students(is_active);
create index if not exists students_archived_at_idx on public.students(archived_at);

------------------------------------------------------------
-- 2) Simplify secure dashboard roles
--    Supported: admin, teacher, rebbe, support_staff
------------------------------------------------------------

update public.user_roles
set role = 'support_staff'
where role in ('therapist', 'office', 'store', 'support', 'staff');

alter table public.user_roles drop constraint if exists user_roles_role_check;

alter table public.user_roles
  add constraint user_roles_role_check
  check (role in ('admin', 'teacher', 'rebbe', 'support_staff'));

------------------------------------------------------------
-- 3) App-layer audit table for secure admin operations
------------------------------------------------------------

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  user_id uuid,
  user_name text not null default '',
  action text not null,
  target_table text not null,
  target_id text not null,
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_action_idx on public.audit_logs(action);
create index if not exists audit_logs_target_idx on public.audit_logs(target_table, target_id);

alter table public.audit_logs enable row level security;

drop policy if exists audit_logs_admin_select on public.audit_logs;
drop policy if exists audit_logs_admin_insert on public.audit_logs;
drop policy if exists audit_logs_admin_update on public.audit_logs;
drop policy if exists audit_logs_admin_delete on public.audit_logs;

create policy audit_logs_admin_select
on public.audit_logs
for select
to authenticated
using (public.dashboard_is_admin());

create policy audit_logs_admin_insert
on public.audit_logs
for insert
to authenticated
with check (public.dashboard_is_admin());

create policy audit_logs_admin_update
on public.audit_logs
for update
to authenticated
using (false)
with check (false);

create policy audit_logs_admin_delete
on public.audit_logs
for delete
to authenticated
using (false);

grant select, insert on table public.audit_logs to authenticated;
revoke all on table public.audit_logs from anon;

commit;
